//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vidly.ServiceReturns1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VATCountryDTO", Namespace="http://schemas.datacontract.org/2004/07/WcfReturnsService1")]
    [System.SerializableAttribute()]
    public partial class VATCountryDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryISO2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryISO3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryISONumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryRepCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CurrencyIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EffDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> EndEffDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RegionIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SupportedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TAIDCountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TAIDGlobalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryISO2 {
            get {
                return this.CountryISO2Field;
            }
            set {
                if ((object.ReferenceEquals(this.CountryISO2Field, value) != true)) {
                    this.CountryISO2Field = value;
                    this.RaisePropertyChanged("CountryISO2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryISO3 {
            get {
                return this.CountryISO3Field;
            }
            set {
                if ((object.ReferenceEquals(this.CountryISO3Field, value) != true)) {
                    this.CountryISO3Field = value;
                    this.RaisePropertyChanged("CountryISO3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryISONum {
            get {
                return this.CountryISONumField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryISONumField, value) != true)) {
                    this.CountryISONumField = value;
                    this.RaisePropertyChanged("CountryISONum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryName {
            get {
                return this.CountryNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryNameField, value) != true)) {
                    this.CountryNameField = value;
                    this.RaisePropertyChanged("CountryName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryRepCode {
            get {
                return this.CountryRepCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryRepCodeField, value) != true)) {
                    this.CountryRepCodeField = value;
                    this.RaisePropertyChanged("CountryRepCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CurrencyID {
            get {
                return this.CurrencyIDField;
            }
            set {
                if ((this.CurrencyIDField.Equals(value) != true)) {
                    this.CurrencyIDField = value;
                    this.RaisePropertyChanged("CurrencyID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EffDate {
            get {
                return this.EffDateField;
            }
            set {
                if ((this.EffDateField.Equals(value) != true)) {
                    this.EffDateField = value;
                    this.RaisePropertyChanged("EffDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> EndEffDate {
            get {
                return this.EndEffDateField;
            }
            set {
                if ((this.EndEffDateField.Equals(value) != true)) {
                    this.EndEffDateField = value;
                    this.RaisePropertyChanged("EndEffDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RegionID {
            get {
                return this.RegionIDField;
            }
            set {
                if ((this.RegionIDField.Equals(value) != true)) {
                    this.RegionIDField = value;
                    this.RaisePropertyChanged("RegionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Supported {
            get {
                return this.SupportedField;
            }
            set {
                if ((this.SupportedField.Equals(value) != true)) {
                    this.SupportedField = value;
                    this.RaisePropertyChanged("Supported");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TAIDCountry {
            get {
                return this.TAIDCountryField;
            }
            set {
                if ((this.TAIDCountryField.Equals(value) != true)) {
                    this.TAIDCountryField = value;
                    this.RaisePropertyChanged("TAIDCountry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TAIDGlobal {
            get {
                return this.TAIDGlobalField;
            }
            set {
                if ((this.TAIDGlobalField.Equals(value) != true)) {
                    this.TAIDGlobalField = value;
                    this.RaisePropertyChanged("TAIDGlobal");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VATLineItemRefDTO", Namespace="http://schemas.datacontract.org/2004/07/WcfReturnsService1")]
    [System.SerializableAttribute()]
    public partial class VATLineItemRefDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VATLineItemRefCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VATLineItemRefDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VATLineItemRefIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Vidly.ServiceReturns1.VATLineItemRefJurisdictionReportCodeDTO[] VATLineItemRefJurisdictionReportCodesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Vidly.ServiceReturns1.VATLineItemRefJurisdictionDTO[] VATLineItemRefJurisdictionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VATLineItemRefTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short VATLineItemRefTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VATLineItemRefCode {
            get {
                return this.VATLineItemRefCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.VATLineItemRefCodeField, value) != true)) {
                    this.VATLineItemRefCodeField = value;
                    this.RaisePropertyChanged("VATLineItemRefCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VATLineItemRefDescription {
            get {
                return this.VATLineItemRefDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.VATLineItemRefDescriptionField, value) != true)) {
                    this.VATLineItemRefDescriptionField = value;
                    this.RaisePropertyChanged("VATLineItemRefDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VATLineItemRefID {
            get {
                return this.VATLineItemRefIDField;
            }
            set {
                if ((this.VATLineItemRefIDField.Equals(value) != true)) {
                    this.VATLineItemRefIDField = value;
                    this.RaisePropertyChanged("VATLineItemRefID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Vidly.ServiceReturns1.VATLineItemRefJurisdictionReportCodeDTO[] VATLineItemRefJurisdictionReportCodes {
            get {
                return this.VATLineItemRefJurisdictionReportCodesField;
            }
            set {
                if ((object.ReferenceEquals(this.VATLineItemRefJurisdictionReportCodesField, value) != true)) {
                    this.VATLineItemRefJurisdictionReportCodesField = value;
                    this.RaisePropertyChanged("VATLineItemRefJurisdictionReportCodes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Vidly.ServiceReturns1.VATLineItemRefJurisdictionDTO[] VATLineItemRefJurisdictions {
            get {
                return this.VATLineItemRefJurisdictionsField;
            }
            set {
                if ((object.ReferenceEquals(this.VATLineItemRefJurisdictionsField, value) != true)) {
                    this.VATLineItemRefJurisdictionsField = value;
                    this.RaisePropertyChanged("VATLineItemRefJurisdictions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VATLineItemRefText {
            get {
                return this.VATLineItemRefTextField;
            }
            set {
                if ((object.ReferenceEquals(this.VATLineItemRefTextField, value) != true)) {
                    this.VATLineItemRefTextField = value;
                    this.RaisePropertyChanged("VATLineItemRefText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short VATLineItemRefType {
            get {
                return this.VATLineItemRefTypeField;
            }
            set {
                if ((this.VATLineItemRefTypeField.Equals(value) != true)) {
                    this.VATLineItemRefTypeField = value;
                    this.RaisePropertyChanged("VATLineItemRefType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VATLineItemRefJurisdictionReportCodeDTO", Namespace="http://schemas.datacontract.org/2004/07/WcfReturnsService1")]
    [System.SerializableAttribute()]
    public partial class VATLineItemRefJurisdictionReportCodeDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EffDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> EndEffDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReportCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReportCodeDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReportCodeDescriptionNative1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReportCodeDescriptionNative2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReportCodeDescriptionNative3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TAIDCountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TAIDGlobalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TAIDJurisdictionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VATLineItemRefIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VATLineItemRef_VATLineItemRefIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EffDate {
            get {
                return this.EffDateField;
            }
            set {
                if ((this.EffDateField.Equals(value) != true)) {
                    this.EffDateField = value;
                    this.RaisePropertyChanged("EffDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> EndEffDate {
            get {
                return this.EndEffDateField;
            }
            set {
                if ((this.EndEffDateField.Equals(value) != true)) {
                    this.EndEffDateField = value;
                    this.RaisePropertyChanged("EndEffDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReportCode {
            get {
                return this.ReportCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ReportCodeField, value) != true)) {
                    this.ReportCodeField = value;
                    this.RaisePropertyChanged("ReportCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReportCodeDescription {
            get {
                return this.ReportCodeDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ReportCodeDescriptionField, value) != true)) {
                    this.ReportCodeDescriptionField = value;
                    this.RaisePropertyChanged("ReportCodeDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReportCodeDescriptionNative1 {
            get {
                return this.ReportCodeDescriptionNative1Field;
            }
            set {
                if ((object.ReferenceEquals(this.ReportCodeDescriptionNative1Field, value) != true)) {
                    this.ReportCodeDescriptionNative1Field = value;
                    this.RaisePropertyChanged("ReportCodeDescriptionNative1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReportCodeDescriptionNative2 {
            get {
                return this.ReportCodeDescriptionNative2Field;
            }
            set {
                if ((object.ReferenceEquals(this.ReportCodeDescriptionNative2Field, value) != true)) {
                    this.ReportCodeDescriptionNative2Field = value;
                    this.RaisePropertyChanged("ReportCodeDescriptionNative2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReportCodeDescriptionNative3 {
            get {
                return this.ReportCodeDescriptionNative3Field;
            }
            set {
                if ((object.ReferenceEquals(this.ReportCodeDescriptionNative3Field, value) != true)) {
                    this.ReportCodeDescriptionNative3Field = value;
                    this.RaisePropertyChanged("ReportCodeDescriptionNative3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TAIDCountry {
            get {
                return this.TAIDCountryField;
            }
            set {
                if ((this.TAIDCountryField.Equals(value) != true)) {
                    this.TAIDCountryField = value;
                    this.RaisePropertyChanged("TAIDCountry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TAIDGlobal {
            get {
                return this.TAIDGlobalField;
            }
            set {
                if ((this.TAIDGlobalField.Equals(value) != true)) {
                    this.TAIDGlobalField = value;
                    this.RaisePropertyChanged("TAIDGlobal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TAIDJurisdiction {
            get {
                return this.TAIDJurisdictionField;
            }
            set {
                if ((this.TAIDJurisdictionField.Equals(value) != true)) {
                    this.TAIDJurisdictionField = value;
                    this.RaisePropertyChanged("TAIDJurisdiction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VATLineItemRefID {
            get {
                return this.VATLineItemRefIDField;
            }
            set {
                if ((this.VATLineItemRefIDField.Equals(value) != true)) {
                    this.VATLineItemRefIDField = value;
                    this.RaisePropertyChanged("VATLineItemRefID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VATLineItemRef_VATLineItemRefID {
            get {
                return this.VATLineItemRef_VATLineItemRefIDField;
            }
            set {
                if ((this.VATLineItemRef_VATLineItemRefIDField.Equals(value) != true)) {
                    this.VATLineItemRef_VATLineItemRefIDField = value;
                    this.RaisePropertyChanged("VATLineItemRef_VATLineItemRefID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VATLineItemRefJurisdictionDTO", Namespace="http://schemas.datacontract.org/2004/07/WcfReturnsService1")]
    [System.SerializableAttribute()]
    public partial class VATLineItemRefJurisdictionDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EffDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> EndEffDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TAIDCountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TAIDGlobalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TAIDJurisdictionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TaxCodeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VATLineItemRefIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VATLineItemRef_VATLineItemRefIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EffDate {
            get {
                return this.EffDateField;
            }
            set {
                if ((this.EffDateField.Equals(value) != true)) {
                    this.EffDateField = value;
                    this.RaisePropertyChanged("EffDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> EndEffDate {
            get {
                return this.EndEffDateField;
            }
            set {
                if ((this.EndEffDateField.Equals(value) != true)) {
                    this.EndEffDateField = value;
                    this.RaisePropertyChanged("EndEffDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TAIDCountry {
            get {
                return this.TAIDCountryField;
            }
            set {
                if ((this.TAIDCountryField.Equals(value) != true)) {
                    this.TAIDCountryField = value;
                    this.RaisePropertyChanged("TAIDCountry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TAIDGlobal {
            get {
                return this.TAIDGlobalField;
            }
            set {
                if ((this.TAIDGlobalField.Equals(value) != true)) {
                    this.TAIDGlobalField = value;
                    this.RaisePropertyChanged("TAIDGlobal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TAIDJurisdiction {
            get {
                return this.TAIDJurisdictionField;
            }
            set {
                if ((this.TAIDJurisdictionField.Equals(value) != true)) {
                    this.TAIDJurisdictionField = value;
                    this.RaisePropertyChanged("TAIDJurisdiction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TaxCodeID {
            get {
                return this.TaxCodeIDField;
            }
            set {
                if ((this.TaxCodeIDField.Equals(value) != true)) {
                    this.TaxCodeIDField = value;
                    this.RaisePropertyChanged("TaxCodeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VATLineItemRefID {
            get {
                return this.VATLineItemRefIDField;
            }
            set {
                if ((this.VATLineItemRefIDField.Equals(value) != true)) {
                    this.VATLineItemRefIDField = value;
                    this.RaisePropertyChanged("VATLineItemRefID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VATLineItemRef_VATLineItemRefID {
            get {
                return this.VATLineItemRef_VATLineItemRefIDField;
            }
            set {
                if ((this.VATLineItemRef_VATLineItemRefIDField.Equals(value) != true)) {
                    this.VATLineItemRef_VATLineItemRefIDField = value;
                    this.RaisePropertyChanged("VATLineItemRef_VATLineItemRefID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReturns1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCountries", ReplyAction="http://tempuri.org/IService1/GetCountriesResponse")]
        Vidly.ServiceReturns1.VATCountryDTO[] GetCountries();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCountries", ReplyAction="http://tempuri.org/IService1/GetCountriesResponse")]
        System.Threading.Tasks.Task<Vidly.ServiceReturns1.VATCountryDTO[]> GetCountriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCountry", ReplyAction="http://tempuri.org/IService1/GetCountryResponse")]
        Vidly.ServiceReturns1.VATCountryDTO GetCountry(string ISO3);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCountry", ReplyAction="http://tempuri.org/IService1/GetCountryResponse")]
        System.Threading.Tasks.Task<Vidly.ServiceReturns1.VATCountryDTO> GetCountryAsync(string ISO3);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetLineItemRefs", ReplyAction="http://tempuri.org/IService1/GetLineItemRefsResponse")]
        Vidly.ServiceReturns1.VATLineItemRefDTO[] GetLineItemRefs();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetLineItemRefs", ReplyAction="http://tempuri.org/IService1/GetLineItemRefsResponse")]
        System.Threading.Tasks.Task<Vidly.ServiceReturns1.VATLineItemRefDTO[]> GetLineItemRefsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetLineItemRef", ReplyAction="http://tempuri.org/IService1/GetLineItemRefResponse")]
        Vidly.ServiceReturns1.VATLineItemRefDTO GetLineItemRef(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetLineItemRef", ReplyAction="http://tempuri.org/IService1/GetLineItemRefResponse")]
        System.Threading.Tasks.Task<Vidly.ServiceReturns1.VATLineItemRefDTO> GetLineItemRefAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateLineItemRef", ReplyAction="http://tempuri.org/IService1/CreateLineItemRefResponse")]
        void CreateLineItemRef(Vidly.ServiceReturns1.VATLineItemRefDTO new_lir_dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateLineItemRef", ReplyAction="http://tempuri.org/IService1/CreateLineItemRefResponse")]
        System.Threading.Tasks.Task CreateLineItemRefAsync(Vidly.ServiceReturns1.VATLineItemRefDTO new_lir_dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteLineItemRef", ReplyAction="http://tempuri.org/IService1/DeleteLineItemRefResponse")]
        void DeleteLineItemRef(Vidly.ServiceReturns1.VATLineItemRefDTO new_lir_dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteLineItemRef", ReplyAction="http://tempuri.org/IService1/DeleteLineItemRefResponse")]
        System.Threading.Tasks.Task DeleteLineItemRefAsync(Vidly.ServiceReturns1.VATLineItemRefDTO new_lir_dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateCountry", ReplyAction="http://tempuri.org/IService1/CreateCountryResponse")]
        void CreateCountry(Vidly.ServiceReturns1.VATCountryDTO new_ctry_dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateCountry", ReplyAction="http://tempuri.org/IService1/CreateCountryResponse")]
        System.Threading.Tasks.Task CreateCountryAsync(Vidly.ServiceReturns1.VATCountryDTO new_ctry_dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteCountry", ReplyAction="http://tempuri.org/IService1/DeleteCountryResponse")]
        void DeleteCountry(Vidly.ServiceReturns1.VATCountryDTO new_ctry_dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteCountry", ReplyAction="http://tempuri.org/IService1/DeleteCountryResponse")]
        System.Threading.Tasks.Task DeleteCountryAsync(Vidly.ServiceReturns1.VATCountryDTO new_ctry_dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateLineItemRef", ReplyAction="http://tempuri.org/IService1/UpdateLineItemRefResponse")]
        void UpdateLineItemRef(Vidly.ServiceReturns1.VATLineItemRefDTO lir);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateLineItemRef", ReplyAction="http://tempuri.org/IService1/UpdateLineItemRefResponse")]
        System.Threading.Tasks.Task UpdateLineItemRefAsync(Vidly.ServiceReturns1.VATLineItemRefDTO lir);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateCountry", ReplyAction="http://tempuri.org/IService1/UpdateCountryResponse")]
        void UpdateCountry(Vidly.ServiceReturns1.VATCountryDTO country);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateCountry", ReplyAction="http://tempuri.org/IService1/UpdateCountryResponse")]
        System.Threading.Tasks.Task UpdateCountryAsync(Vidly.ServiceReturns1.VATCountryDTO country);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Vidly.ServiceReturns1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Vidly.ServiceReturns1.IService1>, Vidly.ServiceReturns1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Vidly.ServiceReturns1.VATCountryDTO[] GetCountries() {
            return base.Channel.GetCountries();
        }
        
        public System.Threading.Tasks.Task<Vidly.ServiceReturns1.VATCountryDTO[]> GetCountriesAsync() {
            return base.Channel.GetCountriesAsync();
        }
        
        public Vidly.ServiceReturns1.VATCountryDTO GetCountry(string ISO3) {
            return base.Channel.GetCountry(ISO3);
        }
        
        public System.Threading.Tasks.Task<Vidly.ServiceReturns1.VATCountryDTO> GetCountryAsync(string ISO3) {
            return base.Channel.GetCountryAsync(ISO3);
        }
        
        public Vidly.ServiceReturns1.VATLineItemRefDTO[] GetLineItemRefs() {
            return base.Channel.GetLineItemRefs();
        }
        
        public System.Threading.Tasks.Task<Vidly.ServiceReturns1.VATLineItemRefDTO[]> GetLineItemRefsAsync() {
            return base.Channel.GetLineItemRefsAsync();
        }
        
        public Vidly.ServiceReturns1.VATLineItemRefDTO GetLineItemRef(int id) {
            return base.Channel.GetLineItemRef(id);
        }
        
        public System.Threading.Tasks.Task<Vidly.ServiceReturns1.VATLineItemRefDTO> GetLineItemRefAsync(int id) {
            return base.Channel.GetLineItemRefAsync(id);
        }
        
        public void CreateLineItemRef(Vidly.ServiceReturns1.VATLineItemRefDTO new_lir_dto) {
            base.Channel.CreateLineItemRef(new_lir_dto);
        }
        
        public System.Threading.Tasks.Task CreateLineItemRefAsync(Vidly.ServiceReturns1.VATLineItemRefDTO new_lir_dto) {
            return base.Channel.CreateLineItemRefAsync(new_lir_dto);
        }
        
        public void DeleteLineItemRef(Vidly.ServiceReturns1.VATLineItemRefDTO new_lir_dto) {
            base.Channel.DeleteLineItemRef(new_lir_dto);
        }
        
        public System.Threading.Tasks.Task DeleteLineItemRefAsync(Vidly.ServiceReturns1.VATLineItemRefDTO new_lir_dto) {
            return base.Channel.DeleteLineItemRefAsync(new_lir_dto);
        }
        
        public void CreateCountry(Vidly.ServiceReturns1.VATCountryDTO new_ctry_dto) {
            base.Channel.CreateCountry(new_ctry_dto);
        }
        
        public System.Threading.Tasks.Task CreateCountryAsync(Vidly.ServiceReturns1.VATCountryDTO new_ctry_dto) {
            return base.Channel.CreateCountryAsync(new_ctry_dto);
        }
        
        public void DeleteCountry(Vidly.ServiceReturns1.VATCountryDTO new_ctry_dto) {
            base.Channel.DeleteCountry(new_ctry_dto);
        }
        
        public System.Threading.Tasks.Task DeleteCountryAsync(Vidly.ServiceReturns1.VATCountryDTO new_ctry_dto) {
            return base.Channel.DeleteCountryAsync(new_ctry_dto);
        }
        
        public void UpdateLineItemRef(Vidly.ServiceReturns1.VATLineItemRefDTO lir) {
            base.Channel.UpdateLineItemRef(lir);
        }
        
        public System.Threading.Tasks.Task UpdateLineItemRefAsync(Vidly.ServiceReturns1.VATLineItemRefDTO lir) {
            return base.Channel.UpdateLineItemRefAsync(lir);
        }
        
        public void UpdateCountry(Vidly.ServiceReturns1.VATCountryDTO country) {
            base.Channel.UpdateCountry(country);
        }
        
        public System.Threading.Tasks.Task UpdateCountryAsync(Vidly.ServiceReturns1.VATCountryDTO country) {
            return base.Channel.UpdateCountryAsync(country);
        }
    }
}
